version: 2
updates:
  - package-ecosystem: "npm"  
    directory: "/"  
    schedule:
      interval: "weekly"  
    commit-message:
      prefix: "deps"  
    pull-request-branch-name:
      separator: "-"  
    target-branch: "dev"  
    open-pull-requests-limit: 10  
